/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author 824737
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        configurarFormulario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemArquivoSeparador = new javax.swing.JPopupMenu.Separator();
        menuItemArquivoSair = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuItemCadastrarGeral = new javax.swing.JMenuItem();
        menuItemCadastrarFuncionarios = new javax.swing.JMenuItem();
        menuItemCadastroVisita = new javax.swing.JMenuItem();
        menuItemCadastroEncomenda = new javax.swing.JMenuItem();
        menuItemCadastrarEstacionamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");
        menuArquivo.add(menuItemArquivoSeparador);

        menuItemArquivoSair.setText("Sair");
        menuItemArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemArquivoSair);

        barraMenu.add(menuArquivo);

        menuCadastrar.setText("Cadastrar");

        menuItemCadastrarGeral.setText("Pessoa");
        menuItemCadastrarGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarGeralActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarGeral);

        menuItemCadastrarFuncionarios.setText("Funcionários");
        menuItemCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarFuncionariosActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarFuncionarios);

        menuItemCadastroVisita.setText("Visita");
        menuItemCadastroVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroVisitaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastroVisita);

        menuItemCadastroEncomenda.setText("Encomenda");
        menuItemCadastroEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroEncomendaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastroEncomenda);

        menuItemCadastrarEstacionamento.setText("Estacionamento");
        menuItemCadastrarEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarEstacionamentoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadastrarEstacionamento);

        barraMenu.add(menuCadastrar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadastrarEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarEstacionamentoActionPerformed
        abrirFormulario(new FormCadastroCarro());
    }//GEN-LAST:event_menuItemCadastrarEstacionamentoActionPerformed

    private void menuItemCadastroEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroEncomendaActionPerformed
        abrirFormulario(new FormCadastroEncomendas());
    }//GEN-LAST:event_menuItemCadastroEncomendaActionPerformed

    private void menuItemCadastroVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroVisitaActionPerformed
        abrirFormulario(new FormCadastroVisita());
    }//GEN-LAST:event_menuItemCadastroVisitaActionPerformed

    private void menuItemCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarFuncionariosActionPerformed
        abrirFormulario(new FormCadastrarFuncionarios());
    }//GEN-LAST:event_menuItemCadastrarFuncionariosActionPerformed

    private void menuItemCadastrarGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarGeralActionPerformed
        abrirFormulario(new FormCadastrarGeral());
    }//GEN-LAST:event_menuItemCadastrarGeralActionPerformed

    private void menuItemArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemArquivoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuItemArquivoSair;
    private javax.swing.JPopupMenu.Separator menuItemArquivoSeparador;
    private javax.swing.JMenuItem menuItemCadastrarEstacionamento;
    private javax.swing.JMenuItem menuItemCadastrarFuncionarios;
    private javax.swing.JMenuItem menuItemCadastrarGeral;
    private javax.swing.JMenuItem menuItemCadastroEncomenda;
    private javax.swing.JMenuItem menuItemCadastroVisita;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setTitle("Portaria");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void abrirFormulario(JInternalFrame f) {
        if (areaTrabalho.getAllFrames().length == 0) {
            areaTrabalho.add(f);
            centralizarFormulario(f);
            f.setVisible(true);
        }
    }

    public static void centralizarFormulario(JInternalFrame f) {
        Dimension d = f.getDesktopPane().getSize();
        f.setLocation(
                (d.width - f.getSize().width) / 2,
                (d.height - f.getSize().height) / 2
        );
    }


}
