/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appcopa;


import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author lucas
 */
public class FormInterface extends javax.swing.JFrame {

    //lista para compartilhar os dados dos times entre os frames
    protected static List<Selecoes> lista;
    
    public FormInterface() {
        initComponents();
        configurarFormulario();
        //abrirFormularioInterno();
        
        lista = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area = new javax.swing.JDesktopPane();
        lblMascote = new javax.swing.JLabel();
        lblTaca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuTabela = new javax.swing.JMenu();
        menuItemVisualizar = new javax.swing.JMenuItem();
        menuConfrontos = new javax.swing.JMenu();
        menuItemInserir = new javax.swing.JMenu();
        menuItemGrupos = new javax.swing.JMenuItem();
        menuItemMata = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuItemSelecoes = new javax.swing.JMenuItem();
        menuItemDesenvolvedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setBackground(new java.awt.Color(255, 51, 51));

        lblMascote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mascote1.png"))); // NOI18N

        lblTaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/taça.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("COPA DO MUNDO RÚSSIA 2018");

        area.setLayer(lblMascote, javax.swing.JLayeredPane.DEFAULT_LAYER);
        area.setLayer(lblTaca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        area.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(areaLayout.createSequentialGroup()
                        .addComponent(lblMascote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTaca)))
                .addContainerGap())
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMascote)
                    .addComponent(lblTaca))
                .addContainerGap())
        );

        menuTabela.setText("Tabela");

        menuItemVisualizar.setText("Visualizar");
        menuTabela.add(menuItemVisualizar);

        barraMenu.add(menuTabela);

        menuConfrontos.setText("Confrontos");

        menuItemInserir.setText("Inserir placares");

        menuItemGrupos.setText("Fase de grupos");
        menuItemInserir.add(menuItemGrupos);

        menuItemMata.setText("Mata-mata");
        menuItemInserir.add(menuItemMata);

        menuConfrontos.add(menuItemInserir);

        barraMenu.add(menuConfrontos);

        menuSobre.setText("Sobre");

        menuItemSelecoes.setText("Seleções");
        menuSobre.add(menuItemSelecoes);

        menuItemDesenvolvedor.setText("Desenvolvedor");
        menuSobre.add(menuItemDesenvolvedor);

        barraMenu.add(menuSobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane area;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMascote;
    private javax.swing.JLabel lblTaca;
    private javax.swing.JMenu menuConfrontos;
    private javax.swing.JMenuItem menuItemDesenvolvedor;
    private javax.swing.JMenuItem menuItemGrupos;
    private javax.swing.JMenu menuItemInserir;
    private javax.swing.JMenuItem menuItemMata;
    private javax.swing.JMenuItem menuItemSelecoes;
    private javax.swing.JMenuItem menuItemVisualizar;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuTabela;
    // End of variables declaration//GEN-END:variables
    
    private void configurarFormulario(){
        this.setTitle("Interface de múltiplos documentos - MDI");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);      
    }
    
    /*private void abrirFormularioInterno(JInternalFrame f){
        
        if (area.getAllFrames().length == 0){
        area.add(f);
        
        //centralizar o formulario
        Dimension d1 = area.getSize();
        Dimension d2 = f.getSize();
        
        f.setLocation(
            (d1.width-d2.width) /2,
             (d1.height-d2.height) /2
        );
        
        f.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "Você precisa fechar a janela atual"
                    + "antes de abrir a nova janela seu pau na zorba PABLA VITTTTTTAR");
        }
        
    }*/
}
