/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;


public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarMarca = new javax.swing.JMenuItem();
        menuCadastrarChuteiraCampo = new javax.swing.JMenuItem();
        menuCadastrarTenis = new javax.swing.JMenuItem();
        menuCadastrarVestuario = new javax.swing.JMenuItem();
        menuCadastrarAcessorios = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenu();
        menuPesquisarMarca = new javax.swing.JMenuItem();
        menuPesquisarChuteiraCampo = new javax.swing.JMenuItem();
        menuPesquisarTenis = new javax.swing.JMenuItem();
        menuPesquisarVestuario = new javax.swing.JMenuItem();
        menuPesquisarAcessorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        barraMenu.add(menuArquivo);

        menuCadastrar.setText("Cadastrar");

        menuCadastrarMarca.setText("Marca");
        menuCadastrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarMarcaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarMarca);

        menuCadastrarChuteiraCampo.setText("Chuteira");
        menuCadastrarChuteiraCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarChuteiraCampoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarChuteiraCampo);

        menuCadastrarTenis.setText("Tênis");
        menuCadastrarTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarTenisActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarTenis);

        menuCadastrarVestuario.setText("Vestuário");
        menuCadastrarVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarVestuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarVestuario);

        menuCadastrarAcessorios.setText("Acessórios");
        menuCadastrarAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAcessoriosActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAcessorios);

        barraMenu.add(menuCadastrar);

        menuPesquisar.setText("Pesquisar");

        menuPesquisarMarca.setText("Marca");
        menuPesquisarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarMarcaActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarMarca);

        menuPesquisarChuteiraCampo.setText("Chuteira de campo");
        menuPesquisarChuteiraCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarChuteiraCampoActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarChuteiraCampo);

        menuPesquisarTenis.setText("Tênis");
        menuPesquisarTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarTenisActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarTenis);

        menuPesquisarVestuario.setText("Vestuário");
        menuPesquisarVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarVestuarioActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarVestuario);

        menuPesquisarAcessorios.setText("Acessórios");
        menuPesquisarAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarAcessoriosActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuPesquisarAcessorios);

        barraMenu.add(menuPesquisar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarMarcaActionPerformed
        abrirFormulario(new FormCadastrarMarca());
    }//GEN-LAST:event_menuCadastrarMarcaActionPerformed

    private void menuCadastrarChuteiraCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarChuteiraCampoActionPerformed
        abrirFormulario(new FormCadastrarChuteira());
    }//GEN-LAST:event_menuCadastrarChuteiraCampoActionPerformed

    private void menuPesquisarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarMarcaActionPerformed
        //abrirFormulario(new FormPesquisarMarca());
    }//GEN-LAST:event_menuPesquisarMarcaActionPerformed

    private void menuPesquisarChuteiraCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarChuteiraCampoActionPerformed
        //abrirFormulario(new FormPesquisarChuteira());
    }//GEN-LAST:event_menuPesquisarChuteiraCampoActionPerformed

    private void menuCadastrarTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarTenisActionPerformed
        abrirFormulario(new FormCadastrarTenis());
    }//GEN-LAST:event_menuCadastrarTenisActionPerformed

    private void menuCadastrarVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarVestuarioActionPerformed
        abrirFormulario(new FormCadastrarVestuario());
    }//GEN-LAST:event_menuCadastrarVestuarioActionPerformed

    private void menuCadastrarAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAcessoriosActionPerformed
        abrirFormulario(new FormCadastrarAcessorios());
    }//GEN-LAST:event_menuCadastrarAcessoriosActionPerformed

    private void menuPesquisarTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarTenisActionPerformed
        //abrirFormulario(new FormPesquisarTenis());
    }//GEN-LAST:event_menuPesquisarTenisActionPerformed

    private void menuPesquisarVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarVestuarioActionPerformed
        //abrirFormulario(new FormPesquisarVestuario());
    }//GEN-LAST:event_menuPesquisarVestuarioActionPerformed

    private void menuPesquisarAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarAcessoriosActionPerformed
        //abrirFormulario(new FormPesquisarAcessorios());
    }//GEN-LAST:event_menuPesquisarAcessoriosActionPerformed

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarAcessorios;
    private javax.swing.JMenuItem menuCadastrarChuteiraCampo;
    private javax.swing.JMenuItem menuCadastrarMarca;
    private javax.swing.JMenuItem menuCadastrarTenis;
    private javax.swing.JMenuItem menuCadastrarVestuario;
    private javax.swing.JMenu menuPesquisar;
    private javax.swing.JMenuItem menuPesquisarAcessorios;
    private javax.swing.JMenuItem menuPesquisarChuteiraCampo;
    private javax.swing.JMenuItem menuPesquisarMarca;
    private javax.swing.JMenuItem menuPesquisarTenis;
    private javax.swing.JMenuItem menuPesquisarVestuario;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setTitle("Controle Estoque");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void abrirFormulario(JInternalFrame f) {
        if (areaTrabalho.getAllFrames().length == 0) {
            areaTrabalho.add(f);
            centralizarFormulario(f);
            f.setVisible(true);
        }
    }

    public static void centralizarFormulario(JInternalFrame f) {
        Dimension d = f.getDesktopPane().getSize();
        f.setLocation(
                (d.width - f.getSize().width) / 2,
                (d.height - f.getSize().height) / 2
        );
    }

}
