# -*- coding: utf-8 -*-
"""FOURIER_FTT_IFTT_GRAFICOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9p_d02buU19fSetYFJ8NSBNUlfzs4PD

# TRANSFORMADA DE FOURIER

Nesta implementação utilizamos as bibliotecas numpy, para a criação de arrays, além da matplotlib que permite a impressão dos gráficos necessários. Inicialmente foram gerados números aleatórios que estão entre 0 e 100, em um intervalo fixo de 0 a 1.0. Sabendo que a transformada de fourier é a soma de duas ondas senoidais, fazemos a soma de duas ondas com frquência de 40hz e 90hz.
"""

import numpy as np 
import matplotlib.pyplot as plt 
t = np.linspace(0, 1.0, 100) 
soma_ondas_senoidais = np.sin(40 * 2 * np.pi * t) + 0.5 * np.sin(90 * 2 * np.pi * t)
plt.ylabel("AMPLITUDE")
plt.xlabel("TEMPO (segundos)")
plt.title('TRANSFORMADA DE FOURIER')
plt.plot(t, soma_ondas_senoidais)

"""# TRANSFORMADA RÁPIDA DE FOURIER

Em sequência realizaremos o cálculo do espectro da frequência por meio da FFT, pois de acordo com cada saída numéria a frequência muda. Na criação do gráfico de amplitude da FFT, usamos o período, que foi inicialmente definido por t[1] - t[0], e em seguida defini-se a frquência, usando o número de amostras geradas no início com o tamanho da soma de ondas senoidais.
"""

fast_fourier_transform = np.fft.fft(soma_ondas_senoidais) 
periodo = t[1] - t[0] 
amostras = soma_ondas_senoidais.size 
f = np.fft.fftfreq(len(soma_ondas_senoidais), periodo)
frequencias = f[:amostras // 2]
amplitudes = np.abs(fast_fourier_transform)[:amostras // 2] * 1 / amostras 
plt.ylabel("AMPLITUDE")
plt.xlabel("FREQUÊNCIA (Hertz)")
plt.title('TRANSFORMADA RÁPIDA DE FOURIER')
plt.xlim([0,150])
plt.bar(frequencias, amplitudes, width=2.0)

"""# TRANSFORMADA INVERSA DE FOURIER

Realizando o cálculo da iFFT, com auxílio da biblioteca, e criando o respectivo gráfico
"""

inverse_fourier_transform = np.fft.ifft(fast_fourier_transform) 
plt.ylabel("AMPLITUDE")
plt.xlabel("TEMPO (segundos)")
plt.title('TRANSFORMADA INVERSA DE FOURIER')
plt.plot(t,inverse_fourier_transform)

"""# GRÁFICOS"""

plt.figure(1)
plt.subplot(2,2,1)
plt.ylabel("AMPLITUDE")
plt.xlabel("TEMPO (segundos)")
plt.title('TRANSFORMADA DE FOURIER')
plt.plot(t, soma_ondas_senoidais)
plt.subplot(2,2,2)
plt.ylabel("AMPLITUDE")
plt.xlabel("Frequência (Hz)")
plt.title('TRANSFORMADA RÁPIDA DE FOURIER')
plt.xlim([0,150])
plt.bar(frequencias, amplitudes, width=2.0)
plt.subplot(2,2,3)
plt.ylabel("AMPLITUDE")
plt.xlabel("TEMPO (segundos)")
plt.title('TRANSFORMADA INVERSA DE FOURIER')
plt.plot(t,inverse_fourier_transform)
plt.tight_layout()