/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula05;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 826274
 */
public class FormMDI extends javax.swing.JFrame {
    
    //lista dinamica contendo dados dos alunos q 
    //sera compartilhada entre os frames
    protected static List<Aluno> lista;
    
    public FormMDI() {
        initComponents();
        configurarFormulario();
        
        lista = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemImportar = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuItemAluno = new javax.swing.JMenuItem();
        menuItemProfessor = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenu();
        menuItemPesquisarAluno = new javax.swing.JMenuItem();
        menuItemPesquisarProfessor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuItemImportar.setText("Abrir");
        menuItemImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemImportarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemImportar);

        menuItemSair.setText("Sair");
        menuArquivo.add(menuItemSair);

        barraMenu.add(menuArquivo);

        menuCadastrar.setText("Cadastrar");

        menuItemAluno.setForeground(new java.awt.Color(240, 240, 240));
        menuItemAluno.setText("Aluno");
        menuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlunoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemAluno);

        menuItemProfessor.setText("Professor");
        menuItemProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfessorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemProfessor);

        barraMenu.add(menuCadastrar);

        menuPesquisar.setText("Pesquisar");

        menuItemPesquisarAluno.setText("Aluno");
        menuItemPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPesquisarAlunoActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuItemPesquisarAluno);

        menuItemPesquisarProfessor.setText("Professor");
        menuItemPesquisarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPesquisarProfessorActionPerformed(evt);
            }
        });
        menuPesquisar.add(menuItemPesquisarProfessor);

        barraMenu.add(menuPesquisar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlunoActionPerformed
        abrirFormularioInterno(new FormCadastrarAluno());
    }//GEN-LAST:event_menuItemAlunoActionPerformed

    private void menuItemProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfessorActionPerformed
        abrirFormularioInterno(new FormCadastrarProfessor());
    }//GEN-LAST:event_menuItemProfessorActionPerformed

    private void menuItemPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPesquisarAlunoActionPerformed
        abrirFormularioInterno(new FormPesquisarAluno());
    }//GEN-LAST:event_menuItemPesquisarAlunoActionPerformed

    private void menuItemPesquisarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPesquisarProfessorActionPerformed
        //abrirFormularioInterno(new FormPesquisarProfessor());
    }//GEN-LAST:event_menuItemPesquisarProfessorActionPerformed

    private void menuItemImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemImportarActionPerformed
        
        JFileChooser dlg = new JFileChooser();
        dlg.setDialogTitle("Selecione o arquivo");
        dlg.setDialogType(JFileChooser.OPEN_DIALOG);
        dlg.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        if(dlg.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
        
            File nomearquivo = dlg.getSelectedFile().getAbsoluteFile();
        
            try{
                FileReader fr = new FileReader(nomearquivo);
                BufferedReader br = new BufferedReader(fr);
                String linha = "";
                while((linha = br.readLine())!=null){
                    String dados[] = linha.split(";");
                    Aluno a = new Aluno(
                        Integer.parseInt(dados[0]),
                        dados[1],
                        dados[2]
                    );
                    lista.add(a);
                }
                br.close();
            }catch (Exception e){
                System.out.println("ERRO: " + e.getMessage());
            }
        
                JOptionPane.showMessageDialog(null, "Importação realizada com sucesso!");
            }
    }//GEN-LAST:event_menuItemImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane area;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuItemAluno;
    private javax.swing.JMenuItem menuItemImportar;
    private javax.swing.JMenuItem menuItemPesquisarAluno;
    private javax.swing.JMenuItem menuItemPesquisarProfessor;
    private javax.swing.JMenuItem menuItemProfessor;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuPesquisar;
    // End of variables declaration//GEN-END:variables
    
    private void configurarFormulario(){
        this.setTitle("Interface de múltiplos documentos - MDI");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);      
    }
    
    private void abrirFormularioInterno(JInternalFrame f){
        
        if (area.getAllFrames().length == 0){
        area.add(f);
        
        //centralizar o formulario
        Dimension d1 = area.getSize();
        Dimension d2 = f.getSize();
        
        f.setLocation(
            (d1.width-d2.width) /2,
             (d1.height-d2.height) /2
        );
        
        f.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "Você precisa fechar a janela atual"
                    + "antes de abrir a nova janela seu pau na zorba PABLA VITTTTTTAR");
        }
        
       
    }
    
  
}
